### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by ducroq** [CLFML/Face_Detector.Cpp#5]
I am wondering how much Windows support we should give...
As you say: Tensorflow project has given up shared library support for Windows. Also, ROS and Windows is a pain in the ass. 
We may even be aiming for embedded linux application at some point?
What do you guys, think?

**Comment by Hoog-V** [comment]
I do strongly agree on giving more attention to linux support! Though a basic non-ROS example on Windows is always useful to have (as long as it is still possible by compiling from source)(which cmake now handles automatically). As soon as more challenges arise when using Windows, I will not hesitate to drop support for Windows. As it is very much a pain to develop for and maintain.
