### ISSUE TITLE
[BUG] ROI is out of bounds when face is detected near the edge of camera frame

### ISSUE THREAD

**Issue by Hoog-V** [CLFML/Face_Detector.Cpp#6]
# Out of bounds ROI
When a face is detected near the edge of an image the ROI returned from the face_detector class will be out of the image bounds. This is not a problem when drawing a rectangle around the face, but it is when trying to crop the image to the roi returned from this class.

## To reproduce
This snippet should provide enough details to reproduce the bug.

```cpp
void main() {
 /* Initialize camera */
    const uint8_t camera_index = 0;
    const uint16_t camera_fps = 30;
    const uint32_t width = 640;
    const uint32_t height = 480;
    cv::VideoCapture cam(camera_index);

    if (cam.isOpened() == false)
    {
        fprintf(stderr, "ERROR: Cannot open camera!\n");
        exit(1);
    }

    cam.set(cv::CAP_PROP_FRAME_WIDTH, width);
    cam.set(cv::CAP_PROP_FRAME_HEIGHT, height);
    cam.set(cv::CAP_PROP_FRAME_COUNT, camera_fps);

    CLFML::FaceDetection::FaceDetector face_det;

    face_det.load_model(CFML_FACE_DETECTOR_CPU_MODEL_PATH);

    cv::Mat cam_frame;
    while (true)
    {
        /* If no frame captured? Try again! */
        if (!cam.read(cam_frame))
        {
            continue;
        }

        /* Load image into model and do inference! */
        face_det.load_image(cam_frame);

        /* Get face_detected value */
        int face_detected = face_det.detected() + 1;
        /* Get the face roi rectangle */
        cv::Rect face_roi = face_det.get_face_roi();

        if (face_detected)
        {
                cv::Mat cropped_image_to_roi = cam_frame(face_roi);
        }
}
}
```
And while running the code, move your face to the edge of the image and then out of the image.
## Error produced

The error produced by opencv:
```
  what():  OpenCV(4.6.0) ./modules/core/src/matrix.cpp:808: error: (-215:Assertion failed) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function 'Mat'
```

## Priority
As this can be patched without any changes to this library, it should be considered a low priority bug.

### Temporary workaround

```cpp
...
if (face_detected) {
            if (face_roi.x >= 0 && face_roi.y >= 0 &&
                face_roi.x + face_roi.width <= cam_frame.cols &&
                face_roi.y + face_roi.height <= cam_frame.rows)
            {
                 cv::Mat cropped_image_to_roi = cam_frame(face_roi);
            }
}
```

**Comment by Hoog-V** [comment]
@ducroq should we fix it in the library or keep the workaround?

**Comment by ducroq** [comment]
@Hoog-V Actually, I would not consider this behavior to be a bug. When the model finds part of a face, it still tries to estimate the ROI of the complete face, also when it is outside of the camera frame. Whenever ROIs are used for cropping, I would restrict the bounding boxes for cropping to the image frame outside of the library

**Comment by Hoog-V** [comment]
Good point! I will close this issue then.
