### ISSUE TITLE
[BUG] Example projects are built when Face_Detector project is imported into another project

### ISSUE THREAD

**Issue by Hoog-V** [CLFML/Face_Detector.Cpp#7]
# Example projects build even when Face_Detector is not the main project

When importing face_detector.cpp into another project, CMake builds the example code. This should be default off according to the CMakeLists file.

## To reproduce

Import the project into another CMake project:

```cmake
cmake_minimum_required(VERSION 3.1...3.14)

project(test_project VERSION 3.11.5 LANGUAGES CXX)

include(FetchContent)
FetchContent_Declare(
        face_detector.cpp
        GIT_REPOSITORY https://github.com/CLFML/Face_Detector.Cpp.git
        GIT_TAG main
)
FetchContent_MakeAvailable(face_detector.cpp)
add_executable(demo ${CMAKE_CURRENT_LIST_DIR}/src/demo.cpp)
target_link_libraries(demo PUBLIC CLFML::face_detector)
```

src/demo.cpp:
```cpp
int main(int argc, char *argv[])
{

}
```

After building you will still find the face_roi_demo example in the build directory. Even though no one asked it to compile.

## Cause
It is probably caused by a typo somewhere in the CMakeLists that detects whether this project is the Main project.

**Comment by ducroq** [comment]
great!
